#pragma config(Motor,  port1,           Transmission,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Conveyor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LLaunch,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           RLaunch,       tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           RLift1,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           RLift2,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           LLift1,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           LLift2,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           RDrive,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          LDrive,        tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "testTransmission.c"
task main()
{
	bool rightLiftMotorForward = true; //Start right lift motor forward for transmission
	bool leftLiftMotorForward = false; //Start left lift motor forward for transmission
	bool con8Dtoggle = false; //Controller button 8D pressed
	bool interrupt = false; //Stop checking for buttons

	while(interrupt == false)
	{

	}
}
